#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kentico.Xperience.CRM.Dynamics.Dataverse.OptionSets
{
	
	
	/// <summary>
	/// If there has been initial communication with this lead.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum initialcommunication
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contacted = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NotContacted = 1,
	}
}
#pragma warning restore CS1591
