#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kentico.Xperience.CRM.Dynamics.Dataverse.OptionSets
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_leadscoretrendoptset
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Improving = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Steady = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Declining = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notenoughinfo = 3,
	}
}
#pragma warning restore CS1591
