//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.OnlineForms;
using CMS.OnlineForms.Types;

[assembly: RegisterBizForm(DancingGoatSubscriptionItem.CLASS_NAME, typeof(DancingGoatSubscriptionItem))]

namespace CMS.OnlineForms.Types
{
	/// <summary>
	/// Represents a content item of type DancingGoatSubscriptionItem.
	/// </summary>
	public partial class DancingGoatSubscriptionItem : BizFormItem
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "BizForm.DancingGoatSubscription";


		/// <summary>
		/// The instance of the class that provides extended API for working with DancingGoatSubscriptionItem fields.
		/// </summary>
		private readonly DancingGoatSubscriptionItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// Email.
		/// </summary>
		[DatabaseField]
		public string Email
		{
			get => ValidationHelper.GetString(GetValue(nameof(Email)), @"");
			set => SetValue(nameof(Email), value);
		}


		/// <summary>
		/// Gets an object that provides extended API for working with DancingGoatSubscriptionItem fields.
		/// </summary>
		[RegisterProperty]
		public DancingGoatSubscriptionItemFields Fields
		{
			get => mFields;
		}


		/// <summary>
		/// Provides extended API for working with DancingGoatSubscriptionItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class DancingGoatSubscriptionItemFields : AbstractHierarchicalObject<DancingGoatSubscriptionItemFields>
		{
			/// <summary>
			/// The content item of type DancingGoatSubscriptionItem that is a target of the extended API.
			/// </summary>
			private readonly DancingGoatSubscriptionItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="DancingGoatSubscriptionItemFields" /> class with the specified content item of type DancingGoatSubscriptionItem.
			/// </summary>
			/// <param name="instance">The content item of type DancingGoatSubscriptionItem that is a target of the extended API.</param>
			public DancingGoatSubscriptionItemFields(DancingGoatSubscriptionItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// Email.
			/// </summary>
			public string Email
			{
				get => mInstance.Email;
				set => mInstance.Email = value;
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="DancingGoatSubscriptionItem" /> class.
		/// </summary>
		public DancingGoatSubscriptionItem() : base(CLASS_NAME)
		{
			mFields = new DancingGoatSubscriptionItemFields(this);
		}

		#endregion
	}
}